### ISSUE TITLE
Cube Viewer: cell enter conflict with cell formatting

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#231] opened 2018-10-02 15:05 UTC
Arc 1.1.3
TM1 11.3.000031
Chrome

I came across a rather disturbing bug. When using the enter & tab keys in the cube viewer you expect the change (if any) made to the cell to be committed and the focus cell to advance either one row down for enter or one column to the right for tab.

However if the number format in the cell contains comma as the thousand separator then it looks like this is being interpreted as a delimiter and the end effect when hitting enter or tab is that the value of the cell is truncated to the first comma (from left) and the cell where enter or tab was presses retains the focus. e.g. if the cell value is "11,111" then after hitting tab the value is "11". If the stating value is "111,999,999" then the value after tab will be "111".
**Cell selected before hitting enter or tab**
![image](https://user-images.githubusercontent.com/29408388/46357496-4b2c6f80-c665-11e8-8be6-d291a101a6cc.png)
**After hitting enter or tab**
![image](https://user-images.githubusercontent.com/29408388/46357510-58e1f500-c665-11e8-9bb1-e8443c645d26.png)

If the comma is removed from the cell contents BEFORE hitting enter or tab then the correct value is committed. e.g.
**Cell selected before hitting enter or tab**
![image](https://user-images.githubusercontent.com/29408388/46357696-b70ed800-c665-11e8-9448-69c1a3b216be.png)
**After hitting enter or tab**
![image](https://user-images.githubusercontent.com/29408388/46357727-c2fa9a00-c665-11e8-8d60-543e0ec591c9.png)

**Comment by cubewise-tryan** [comment] 2018-10-02 21:52
Using tab and enter keys for navigation are not supported at the moment so they will be added as part of the text. Closing this issue as it related/duplicate of #232

**Closed by cubewise-tryan** 2018-10-02 21:52 UTC
Labels: duplicate, enhancement

**Comment by lotsaram** [comment] 2018-10-02 21:59
The point of this as a separate issue was not the lack of navigation but that the wrong value is committed to the database.
