### ISSUE TITLE
TI Launched from ARC not writting to cube (Architect is ok, ARC in Debug mode is OK)

### ISSUE THREAD

**Issue by grandryjn** [cubewise-code/arc-issues#127] opened 2018-06-21 07:19 UTC
Hi,

I just found a weird issue.

I wrote a TI in arc.
When I run it, it seems running but the value is not written to the cube.
When I run in debug the value is pushed to the cube --> all good.
When I run it from perspective the value is pushed to the cube --> all good.

I tried the 3 steps above in different order and I consistently have me the same result.
I tried to close chrome and re-open it, still the same issue.

I restarted ARC service, the issue is still the same.

Detail of the process
Source: ODBC
Plain query (no Parameter passed dynamically)
ARC version: v0.9.7

Let me know if you need additional information.

**Comment by grandryjn** [comment] 2018-06-21 07:56
Hi,

I will try to find something repeatable and provide some instructions.

**Comment by grandryjn** [comment] 2018-06-22 00:10
Hi @cubewise-tryan,

I have been able to narrow it down, just having a minor error in the TI is preventing to write any valid data to the cube.

Here the steps to reproduce it.

Create a New Process
Write the following lines in the prolog

> CellPutS('Hello', 'SYS Parameter', 'Test', 'String');
> CellPutS('Hello', 'SYS Parameter', 'Test3', 'String');

Where Test is a valid element and Test3 is not an element of the dimension.

In ARC when executing the process, there is a popup message with ProcessHasMinorErrors but the valid CellPutS is not comitted to the cube.
In Architect, there is an error message, the valid CellPutS is comitted to the cube.
In ARC when using the debug modes, there is no popup message showing the error, the valid CellPutS is comitted to the cube.

ARC 0.9.7
PA 11.2.00000.27

I can provide the CFG if needed.

**Comment by cubewise-tryan** [comment] 2018-06-22 02:21
Hi @grandryjn ,

I don't think this is caused by Arc as it just executes the TI via the REST API. My guess is that the REST API might have a different transaction mechanism. Can you try executing the TI via Postman (https://code.cubewise.com/blog/mastering-the-tm1-rest-api-with-postman)  and see if you encounter the same issue?

**Comment by lotsaram** [comment] 2018-06-26 22:29
I have raised this as an issue with IBM support. Seems a pretty significant breaking change if TI processes with minor errors don't commit data changes.

**Comment by lotsaram** [comment] 2018-06-28 17:36
FYI I tested this today using PA 2.0.5 | TM1 11.3.00000.27
It seems to be fixed in the latest version.
Although the failure to commit a transaction in the event of minor error isn't explicitly listed as a fixed issue in the 2.0.5 fix list the notes do mention a change to Execute.Process and ExecuteProcess methods and the transaction model and error log status. So it seems with these improvements they also fixed this bug.

**Comment by cubewise-tryan** [comment] 2018-09-27 11:17
Hi @grandryjn  & @lotsaram,

There is a new REST Action called ExecuteWithReturn, Arc will use this in TM1 11.3 IF1 or later.

**Closed by cubewise-tryan** 2018-09-27 11:17 UTC
Labels: fixed, question, upstream
