### ISSUE TITLE
Cells are not editable in latest cube viewer

### ISSUE THREAD

**Issue by RaduCantor** [cubewise-code/arc-issues#132] opened 2018-06-26 07:14 UTC
Arc version 0.9.8
TM1 version 11.1.00000.30
Browser Chrome / Firefox / Edge

None of the input cells in Arc are editable. You cannot write any value, numeric or string. Picklists are working fine, but normal input cells aren't. (please see attached images).

**Arc cube viewer**
![arc 0 98 cubeviewer](https://user-images.githubusercontent.com/39726565/41844578-e61b3a78-7870-11e8-964f-29c09f49acda.PNG)

**Architect (same view)**
![architect view](https://user-images.githubusercontent.com/39726565/41844598-f19ad28c-7870-11e8-8df9-12bdff0c37a4.PNG)

**Comment by cubewise-tryan** [comment] 2018-06-27 02:16
Hi @RaduCantor ,

This is caused by the empty strings, you should be able to edit the non-empty cells. The empty cells issue has been fixed and will be in the next version.

**Closed by cubewise-tryan** 2018-06-27 02:16 UTC
Labels: bug, fixed
