### ISSUE TITLE
Error on Cube View Load

### ISSUE THREAD

**Issue by cubewise-plim** [cubewise-code/arc-issues#69] opened 2018-05-03 01:03 UTC
TM1: 11.1.00000.30
Arc: 0.9.5
OS: Windows 10

Is the Cube View supposed to load upon clicking the view? At the moment, it does not seem to do so. Plus, there is an error on the console. Not sure if this is related:

![image](https://user-images.githubusercontent.com/22946355/39556139-6ef65348-4ec1-11e8-8c9d-7614b75f584c.png)

**Comment by cubewise-tryan** [comment] 2018-05-03 03:40
What do you mean upon clicking the view? When you open a view you need to press the execute button or it will execute if **auto-calculate** is turned on.

**Comment by cubewise-plim** [comment] 2018-05-03 03:45
On the screenshot below I am assuming that the auto-calculate button is "On", but the view is not showing unless I click on the Execute button:

![image](https://user-images.githubusercontent.com/22946355/39559243-0d2100de-4ed8-11e8-8202-0db50165d240.png)

**Comment by cubewise-tryan** [comment] 2018-05-03 04:02
The button in the screenshot is "Off"

**Comment by cubewise-plim** [comment] 2018-05-03 04:06
Had clicked on that and this is what I thought is "Off":

![image](https://user-images.githubusercontent.com/22946355/39559605-d9d810b6-4eda-11e8-80bf-726ad416043c.png)

Where as, this is on (I based it off the slight grayish color):

![image](https://user-images.githubusercontent.com/22946355/39559622-e97628b4-4eda-11e8-85ce-6bb7c07357b6.png)

I had also clicked outside just to make sure that it is not because of the mouse pointer hovering over that.

**Comment by cubewise-tryan** [comment] 2018-05-03 04:17
Can we close this issue?

**Comment by cubewise-tryan** [comment] 2018-05-03 04:27
Hi @cubewise-plim ,

I have had a further look and the issue is related to the type of view. If it is a native view it doesn't execute automatically when opened, an MDX view does. There is a reason for this, in a native view the elements are lazily loaded in the background so the view can't be executed straight away. 

Closing the issue as there isn't an easy workaround.

**Closed by cubewise-tryan** 2018-05-03 04:27 UTC
Labels: invalid, wontfix
